### ISSUE TITLE
Error occurred attempting to read POM

### ISSUE THREAD

**Issue by stefan-g** [CycloneDX/cyclonedx-gradle-plugin#313]
I got the following error when the cyclonedxBom task is excecuted. The problem is there are no infos which artifact is affected. It would be nice to have at least a debug info which artifact was loaded.

An error occurred attempting to read POM
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unknown attribute 'child.scm.url.inherit.append.path' for tag 'scm' (position: START_TAG seen ...d.path="false"\n         child.scm.url.inherit.append.path="false">... @48:52) 
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.checkUnknownAttribute(MavenXpp3Reader.java:161)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseScm(MavenXpp3Reader.java:3743)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2200)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3852)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:609)
	at org.cyclonedx.gradle.MavenHelper.readPom(MavenHelper.java:298)
	at org.cyclonedx.gradle.MavenHelper.extractPom(MavenHelper.java:267)
	at org.cyclonedx.gradle.CycloneDxTask.convertArtifact(CycloneDxTask.java:320)
	at org.cyclonedx.gradle.CycloneDxTask.lambda$null$3(CycloneDxTask.java:166)
	at java.base@17.0.4.1/java.lang.Iterable.forEach(Iterable.java:75)
	at org.cyclonedx.gradle.CycloneDxTask.lambda$createBom$4(CycloneDxTask.java:156)
	at java.base@17.0.4.1/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base@17.0.4.1/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base@17.0.4.1/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@17.0.4.1/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base@17.0.4.1/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base@17.0.4.1/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base@17.0.4.1/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3064)
	at java.base@17.0.4.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.4.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.4.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.4.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.4.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:174)
	at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4.1/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)

**Comment by vvardan007** [comment]
were you able to resolve the issue, could you pls share thee resolution steps
