### ISSUE TITLE
Version 1.8.0 and compatibility with java8

### ISSUE THREAD

**Issue by fserafin** [CycloneDX/cyclonedx-gradle-plugin#357]
Hi,
if I use the plugin version `1.8.0` in a `java8` project, I get this error: `Unsupported class file major version 63`.
I'm using `Gradle 7.5.1,` SDK `Temurin 1.8.0_382`.

I tried with an empty project and this is my `build.gradle`:
```gradle
plugins {
    id 'java'

    id 'org.cyclonedx.bom' version '1.8.0'

}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
```

This is the error that I get:

```
Caused by: org.gradle.api.GradleException: Failed to create Jar file /Users/francesco/.gradle/caches/jars-9/cea29e8500224c3c855df1c997f9a93b/jackson-core-2.15.3.jar.
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.instrument(InstrumentingClasspathFileTransformer.java:137)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:132)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:96)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.transformFile(DefaultCachedClasspathTransformer.java:193)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$cachedFile$6(DefaultCachedClasspathTransformer.java:186)
	at org.gradle.internal.UncheckedException.unchecked(UncheckedException.java:74)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$transformAll$9(DefaultCachedClasspathTransformer.java:233)
	... 2 more
Caused by: java.io.IOException: Failed to process the entry 'META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class' from '/Users/francesco/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.15.3/60d600567c1862840397bf9ff5a92398edc5797b/jackson-core-2.15.3.jar'
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:161)
	at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:91)
	at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.visitEntries(InstrumentingClasspathFileTransformer.java:148)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$instrument$0(InstrumentingClasspathFileTransformer.java:139)
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:66)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:53)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:151)
	... 15 more
```

If I switch to previous version `1.7.4` everything works fine.

**Comment by ThomGeG** [comment]
I've been seeing similar problems and Google led me here. Apparently it's a bug with Gradle itself: https://github.com/gradle/gradle/issues/24390

Having a read through that issue it sounds like the solution is just upgrading to a newer version of Gradle.

**Comment by skhokhlov** [comment]
This is a bug with Gradle support of multi release jars https://github.com/gradle/gradle/issues/24390
