### ISSUE TITLE
Hello, I have encountered such an error, I do not know how to solve it

### ISSUE THREAD

**Issue by wzd-hash** [CycloneDX/cyclonedx-gradle-plugin#359]
![image](https://github.com/CycloneDX/cyclonedx-gradle-plugin/assets/59039445/01d77906-e1ce-4dd7-812e-72e9d36eebf3)

**Comment by glefloch** [comment]
Could you run the command with the -S flag to show the full stack trace ?

**Comment by wzd-hash** [comment]
Do you need this kind of information

E:\Data\project\file\code\KanJing-Android-Research>.\gradlew --init-script .\init.gradle cyclonedxBom -info -S
Initialized native services in: E:\AppData\java\gradle\repository\native
Found daemon DaemonInfo{pid=31984, address=[418e0c28-3ab6-45ee-8234-a554f9552547 port:53547, addresses:[/127.0.0.1]], state=Idle, lastBusy=1698905972834, context=DefaultDaemonContext[uid=00c73fee-3fdd-4a6e-8027-92861e162f7c,javaHome=D:\java\software\jdk\JDK8,daemonRegistryDir=E:\AppData\java\gradle\repository\daemon,pid=31984,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx1536m,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} however its context does not match the desired criteria.
At least one daemon option is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=D:\java\software\jdk\JDK8,daemonRegistryDir=E:\AppData\java\gradle\repository\daemon,pid=19524,idleTimeout=null,priority=NORMAL,daemonOpts=-Xmx2048m,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]
Actual: DefaultDaemonContext[uid=00c73fee-3fdd-4a6e-8027-92861e162f7c,javaHome=D:\java\software\jdk\JDK8,daemonRegistryDir=E:\AppData\java\gradle\repository\daemon,pid=31984,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx1536m,-Dfile.encoding=GBK,-Duser.country=CN,-Duser.language=zh,-Duser.variant]

  Looking for a different daemon...
Removing 0 daemon stop events from registry
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Starting process 'Gradle build daemon'. Working directory: E:\AppData\java\gradle\repository\daemon\6.1.1 Command: D:\java\software\jdk\JDK8\bin\java.exe -Xmx2048m -Dfile.encoding=GBK -Duser.country=CN -Duser.language=zh -Duser.variant -cp E:\AppData\java\gradle\repository\wrapper\dists\gradle-6.1.1-all\cfmwm155h49vnt3hynmlrsdst\gradle-6.1.1\lib\gradle-launcher-6.1.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.1.1
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 8.315 secs.
The client will now receive all logging from the daemon (pid: 31992). The daemon log file: E:\AppData\java\gradle\repository\daemon\6.1.1\daemon-31992.out.log
Starting build in new daemon [memory: 1.9 GB]
Using 8 worker leases.
Starting Build
Settings evaluated using settings file 'E:\Data\project\file\code\KanJing-Android-Research\settings.gradle'.
Projects loaded. Root project using build file 'E:\Data\project\file\code\KanJing-Android-Research\build.gradle'.
Included projects: [root project 'smart-marketing-resource', project ':app', project ':library-aop', project ':library-base', project ':library-common', project ':library-db', project ':library-network', project ':library-widget', project ':md360vrlib', project ':module_live', project ':moudle_config']

> Configure project :
Evaluating root project 'smart-marketing-resource' using build file 'E:\Data\project\file\code\KanJing-Android-Research\build.gradle'.

> Configure project :app
Evaluating project ':app' using build file 'E:\Data\project\file\code\KanJing-Android-Research\app\build.gradle'.
Creating configuration androidTestUtil
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
project.aspectjx=AJXExtension{includes=[[]], excludes=[[androidx, com.google, org.jetbrains.kotlin, com.squareup, android.support, versions.9]], ajcArgs=[[]], enabled=true}

> Configure project :library-aop
Evaluating project ':library-aop' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-aop\build.gradle'.
Creating configuration androidTestUtil

> Configure project :library-base
Evaluating project ':library-base' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-base\build.gradle'.
Creating configuration androidTestUtil
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :library-common
Evaluating project ':library-common' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-common\build.gradle'.
Creating configuration androidTestUtil

> Configure project :library-db
Evaluating project ':library-db' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-db\build.gradle'.
Creating configuration androidTestUtil

> Configure project :library-network
Evaluating project ':library-network' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-network\build.gradle'.
Creating configuration androidTestUtil

> Configure project :library-widget
Evaluating project ':library-widget' using build file 'E:\Data\project\file\code\KanJing-Android-Research\library-widget\build.gradle'.
Creating configuration androidTestUtil

> Configure project :md360vrlib
Evaluating project ':md360vrlib' using build file 'E:\Data\project\file\code\KanJing-Android-Research\md360vrlib\build.gradle'.
Creating configuration androidTestUtil

> Configure project :module_live
Evaluating project ':module_live' using build file 'E:\Data\project\file\code\KanJing-Android-Research\module_live\build.gradle'.
Creating configuration androidTestUtil

> Configure project :moudle_config
Evaluating project ':moudle_config' using build file 'E:\Data\project\file\code\KanJing-Android-Research\moudle_config\build.gradle'.
Creating configuration androidTestUtil
All projects evaluated.
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type com.hujiang.gradle.plugin.android.aspectjx.AJXPlugin expected enum COM_HUJIANG_GRADLE_PLUGIN_ANDROID_ASPECTJX_AJXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.jetbrains.kotlin.gradle.internal.AndroidSubplugin expected enum ORG_JETBRAINS_KOTLIN_GRADLE_INTERNAL_ANDROIDSUBPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.jetbrains.kotlin.gradle.internal.AndroidSubplugin expected enum ORG_JETBRAINS_KOTLIN_GRADLE_INTERNAL_ANDROIDSUBPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Analytics other plugin to proto: Unknown plugin type org.cyclonedx.gradle.CycloneDxPlugin expected enum ORG_CYCLONEDX_GRADLE_CYCLONEDXPLUGIN
Selected primary task 'cyclonedxBom' from project :
Tasks to be executed: [task ':cyclonedxBom', task ':app:cyclonedxBom', task ':library-aop:cyclonedxBom', task ':library-base:cyclonedxBom', task ':library-common:cyclonedxBom', task ':library-db:cyclonedxBom', task ':library-network:cyclonedxBom', task ':library-widget:cyclonedxBom', task ':md360vrlib:cyclonedxBom', task ':module_live:cyclonedxBom', task ':moudle_config:cyclonedxBom']
:cyclonedxBom (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :cyclonedxBom FAILED
Task :cyclonedxBom in app Starting
Caching disabled for task ':cyclonedxBom' because:
  Build cache is disabled
Task ':cyclonedxBom' is not up-to-date because:
  Task has failed previously.
CycloneDX: Parameters
------------------------------------------------------------------------
schemaVersion          : 1.5
includeLicenseText     : true
includeBomSerialNumber : false
includeConfigs         : [runtimeClasspath]
skipConfigs            : [compileClasspath, testCompileClasspath]
skipProjects           : [smart-marketing-resource, yourTestSubProject]
destination            : E:\Data\project\file\code\KanJing-Android-Research\build\reports
outputName             : bom
------------------------------------------------------------------------
CycloneDX: Resolving Dependencies
An unexpected issue occurred attempting to create a PackageURL for :smart-marketing-resource:unspecified
An unexpected issue occurred attempting to create a PackageURL for :smart-marketing-resource:unspecified
An unexpected issue occurred attempting to create a PackageURL for :smart-marketing-resource:unspecified
CycloneDX: Creating BOM
CycloneDX: Writing BOM JSON
CycloneDX: Validating BOM
Task :cyclonedxBom in app Finished
:cyclonedxBom spend 593ms
:cyclonedxBom (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.642 secs.
      00:00.59   :cyclonedxBom

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cyclonedxBom'.
> The BOM does not conform to the CycloneDX BOM standard

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cyclonedxBom'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.gradle.api.GradleException: The BOM does not conform to the CycloneDX BOM standard
        at org.cyclonedx.gradle.CycloneDxTask.writeJSONBom(CycloneDxTask.java:716)
        at org.cyclonedx.gradle.CycloneDxTask.writeBom(CycloneDxTask.java:672)
        at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:399)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at java.util.Optional.orElseGet(Unknown Source)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:63)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at java.util.Optional.map(Unknown Source)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at java.util.Optional.orElseGet(Unknown Source)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 33 more
Caused by: org.cyclonedx.exception.ParseException: $.dependencies[0].ref????·??????° null???é??è????? string
        at org.cyclonedx.parsers.JsonParser.validate(JsonParser.java:177)
        at org.cyclonedx.parsers.JsonParser.validate(JsonParser.java:162)
        at org.cyclonedx.parsers.JsonParser.validate(JsonParser.java:108)
        at org.cyclonedx.gradle.CycloneDxTask.writeJSONBom(CycloneDxTask.java:710)
        ... 104 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 27s
1 actionable task: 1 executed

**Comment by ankursharma180** [comment]
I have just applied plugin, facing similar issue:

* What went wrong:
A problem occurred configuring root project 'library'.
> Could not create task ':cyclonedxBom'.
   > Could not create task of type 'CycloneDxTask'.
      > org.gradle.api.provider.Property.convention(Ljava/lang/Object;)Lorg/gradle/api/provider/Property;

I have a multi module gradle project, so, I've applied below in my root build.gradle
**plugins {
    id 'org.cyclonedx.bom' version '1.8.1'
}**
So, I am facing the error above, can't figure out anything, any solution ?

**Comment by skhokhlov** [comment]
The problem can be related to the charset you're using by default. Please make sure that the gradle files are encoded using UTF-8 and run the plugin with `-Dfile.encoding=UTF-8` command line option to verify it.

**Comment by ThomGeG** [comment]
@ankursharma180 I'm going to take a stab in the dark here and guess you don't have a group ID defined for your sub-project.

If you open the BOM being produced you'll probably see something this:

```
  "dependencies" : [
    {
      "ref" : null,
      "dependsOn" : [
        "pkg:maven/org.springframework.boot/spring-boot-starter-artemis@3.3.2?type=jar",
        "pkg:maven/org.apache.commons/commons-lang3@3.14.0?type=jar"
      ]
    },
```

That `null` is your problem and it stems from the thing you're building a BOM for not having a group id defined in its `build.gradle`.

It's been nearly a year since you raised this so maybe you've figured it out already but I thought I'd leave something for any other people having the same problem.

The plugin itself should maybe be smarter about what to do when people haven't defined a group id.
