### ISSUE TITLE
feedback: release 2.0.0-alpha-0

### ISSUE THREAD

**Issue by jeremylong-snc** [CycloneDX/cyclonedx-gradle-plugin#548]
@skhokhlov via the grapevine I was asked to provide feedback, as such I'm opening this issue as there is no discussion board for the project even though this isn't really an "issue".

**The initial testing of the alpha release looks good.** We did run into an exception due to how a mutli-project gradle **android** build was setup:

```
> Task :app:cyclonedxBom
Error constructing packageUrl for component dependency [redacted.jar]. Skipping...
com.github.packageurl.MalformedPackageURLException: The PackageURL specified is invalid. Maven requires both a namespace and name.
        at com.github.packageurl.PackageURL.verifyTypeConstraints(PackageURL.java:607)
        at com.github.packageurl.PackageURL.<init>(PackageURL.java:105)
        at org.cyclonedx.gradle.utils.DependencyUtils.generatePackageUrl(DependencyUtils.java:133)
        at org.cyclonedx.gradle.SbomBuilder.toDependency(SbomBuilder.java:178)
        at org.cyclonedx.gradle.SbomBuilder.lambda$addDependency$1(SbomBuilder.java:165)
        at java.base@17.0.12/java.lang.Iterable.forEach(Iterable.java:75)
        at org.cyclonedx.gradle.SbomBuilder.addDependency(SbomBuilder.java:163)
        at org.cyclonedx.gradle.SbomBuilder.lambda$buildBom$0(SbomBuilder.java:98)
        at java.base@17.0.12/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
        at org.cyclonedx.gradle.SbomBuilder.buildBom(SbomBuilder.java:97)
        at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:255)
        at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at 
[...........]
```

However, we would have run into a similar issue regardless to the changes in the 2.0.0 release. I'll open another issue with a sample project to replicate - and a proposed solution. I may also suggest 1-2 other minor improvements via PRs - but they should not hold up a release. Although for my purposes I will need #546 merged - but if it doesn't make it I can just build the project locally and use my version until the build-system metadata is added.

**Comment by jeremylong-snc** [comment]
The alpha release looks good! I updated my comment above after researching the stacktrace during bom generation - it is nothing the plugin should "fix".

**Comment by skhokhlov** [comment]
@jeremylong-snc great to hear! Please feel free to raise issues / send PRs for your improvements. FYI, I expect version 2.0.0 to be released on January 16th.
