### ISSUE TITLE
ConcurrentModificationException when working with multiple sub-projects

### ISSUE THREAD

**Issue by uvifian** [CycloneDX/cyclonedx-gradle-plugin#99]
We can see intermittent build failures on projects with multiple (4-5) sub-projects that involve CycloneDx. The stack trace might indicate a Gradle issue but it's in fact very similar to [1], so this is likely with the CycloneDX plugin.

This can be seen in Gradle 6.7. Unfortunately, I can't provide a small test project to reproduce as it only seems to happen on larger projects.

```
Caused by: java.util.ConcurrentModificationException
	at org.gradle.api.internal.DefaultDomainObjectCollection$IteratorImpl.next(DefaultDomainObjectCollection.java:479)
	at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
```

[1] https://github.com/gradle/gradle/issues/10042

**Comment by kmoens** [comment]
I suffer the same problem. It was solved with me (not perfect sadly) by adding a dependency towards the build task as follows:

```
target.tasks.named('cyclonedxBom').configure {
    dependsOn target.tasks.named('build')
}
```

This is not perfect however, but I suspect that this happens because some of my own plugins modify / create configurations during runtime and that this somehow triggers the `ConcurrentModificationException`
